import axiosClient from "./axios";
import type { CheckoutResult } from "./authApi";
import type { SchoolBilling, PlanQuote } from "../types/school";
import type { SchoolClassDetail, SchoolClassRequest, SchoolClassSummary } from "../types/school";

export const schoolBilling = () => axiosClient.get<SchoolBilling>("/school/billing").then(r => r.data);
export const quoteSchoolPlan = (planCode: string) => axiosClient.post<PlanQuote>("/school/billing/quote", { planCode }).then(r => r.data);
export const purchaseSchoolPlan = (planCode: string, expectedAmountVnd: number) => axiosClient.post<CheckoutResult>("/school/billing/checkout", { planCode, expectedAmountVnd }).then(r => r.data);
export const setNextSchoolPlan = (planCode: string) => axiosClient.put<SchoolBilling>("/school/billing/next-plan", { planCode }).then(r => r.data);
const classesPath = (schoolId: string) => `/schools/${schoolId}/classes`;
export const schoolClasses = (schoolId: string) => axiosClient.get<SchoolClassSummary[]>(classesPath(schoolId)).then(r => r.data);
export const schoolClass = (schoolId: string, classId: string) => axiosClient.get<SchoolClassDetail>(`${classesPath(schoolId)}/${classId}`).then(r => r.data);
export const createSchoolClass = (schoolId: string, payload: SchoolClassRequest) => axiosClient.post<SchoolClassDetail>(classesPath(schoolId), payload).then(r => r.data);
export const updateSchoolClass = (schoolId: string, classId: string, payload: SchoolClassRequest) => axiosClient.put<SchoolClassDetail>(`${classesPath(schoolId)}/${classId}`, payload).then(r => r.data);
export const archiveSchoolClass = (schoolId: string, classId: string) => axiosClient.delete<void>(`${classesPath(schoolId)}/${classId}`).then(r => r.data);
export const assignClassTeacher = (schoolId: string, classId: string, teacherId: number) => axiosClient.post(`${classesPath(schoolId)}/${classId}/teachers`, { teacherId }).then(r => r.data);
export const removeClassTeacher = (schoolId: string, classId: string, teacherId: number) => axiosClient.delete(`${classesPath(schoolId)}/${classId}/teachers/${teacherId}`).then(r => r.data);
export const enrollClassStudent = (schoolId: string, classId: string, studentId: number) => axiosClient.post(`${classesPath(schoolId)}/${classId}/students`, { studentId }).then(r => r.data);
export const transferClassStudent = (schoolId: string, classId: string, studentId: number) => axiosClient.put(`${classesPath(schoolId)}/${classId}/students/${studentId}/transfer`).then(r => r.data);
export const removeClassStudent = (schoolId: string, classId: string, studentId: number) => axiosClient.delete(`${classesPath(schoolId)}/${classId}/students/${studentId}`).then(r => r.data);
export type SchoolReportSummary = { schoolId: string; schoolName: string; students: number; teachers: number; managers: number; activeClasses: number; enrolledStudents: number; usedTokens: number; tokenQuota: number | null; licenseEnd: string | null };
export type SchoolReportClass = { id: string; name: string; gradeLevel: number; schoolYear: string; teachers: number; students: number };
export type SchoolImportResult = { total: number; imported: number; failed: number; rows: { row: number; email: string; status: string; message: string }[] };
export type SchoolTokenAudit = { userEmail: string; tokens: number; operation: string; usageMonth: string; recordedAt: string };
const reportPath = (schoolId: string) => `/schools/${schoolId}/reports`;
export const schoolReportSummary = (schoolId: string) => axiosClient.get<SchoolReportSummary>(`${reportPath(schoolId)}/summary`).then(r => r.data);
export const schoolReportClasses = (schoolId: string) => axiosClient.get<SchoolReportClass[]>(`${reportPath(schoolId)}/classes`).then(r => r.data);
export const schoolReportTokenAudit = (schoolId: string) => axiosClient.get<SchoolTokenAudit[]>(`${reportPath(schoolId)}/token-audit`).then(r => r.data);
export const importSchoolUsers = (schoolId: string, file: File) => { const form = new FormData(); form.append("file", file); return axiosClient.post<SchoolImportResult>(`${reportPath(schoolId)}/users/import`, form).then(r => r.data); };
export const downloadSchoolClassesCsv = async (schoolId: string) => {
  const response = await axiosClient.get<Blob>(`${reportPath(schoolId)}/classes.csv`, { responseType: "blob" });
  const url = URL.createObjectURL(response.data);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "danh-sach-lop.csv";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
};
