import { useEffect, useState } from "react";
import LearningIcon from "../../../shared/ui/LearningIcon";
import { Badge, Table } from "@radix-ui/themes";
import { validationRuns, type ValidationRun } from "../api/operationsApi";
import { apiMessage } from "../../../shared/lib/apiError";
import { PageHeader, Panel, Loading, ErrorNotice, Button } from "../../../shared/ui/ManagementUI";

export function ValidationView() {
  const [items, setItems] = useState<ValidationRun[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = async () => { setLoading(true); try { setItems(await validationRuns()); setError(""); } catch (e) { setError(apiMessage(e, "Không thể tải các lần kiểm định.")); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  return <div className="admin-content"><PageHeader title="Kiểm định mô phỏng" description="Theo dõi các lần kiểm tra thực tế của solver và reference solver." action={<Button onClick={() => void load()}><LearningIcon name="refresh" /> Làm mới</Button>} />{error && <ErrorNotice error={error} onRetry={() => void load()} />}{loading ? <Loading /> : <Panel title={`${items.length} lần chạy`}><div className="admin-table-scroll"><Table.Root size="2" variant="ghost" className="admin-table"><Table.Header><Table.Row><Table.ColumnHeaderCell>Thời gian</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Chủ đề</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Schema</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Bộ giải</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Trạng thái</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Lỗi</Table.ColumnHeaderCell></Table.Row></Table.Header><Table.Body>{items.length === 0 ? <Table.Row><Table.Cell colSpan={6} className="admin-empty-table">Chưa có lần kiểm định.</Table.Cell></Table.Row> : items.map(item => <Table.Row key={item.id}><Table.Cell>{new Date(item.createdAt).toLocaleString("vi-VN")}</Table.Cell><Table.Cell>{item.topic}</Table.Cell><Table.Cell>{item.schemaId} <small>{item.schemaVersion}</small></Table.Cell><Table.Cell>{item.solverVersion}</Table.Cell><Table.Cell><Badge color={item.passed ? "cyan" : "red"} size="2">{item.passed ? "Đạt" : "Không đạt"}</Badge></Table.Cell><Table.Cell className="admin-error-cell">{item.errorMessage || "—"}</Table.Cell></Table.Row>)}</Table.Body></Table.Root></div></Panel>}</div>;
}